global:
  scrape_interval: 1s
  evaluation_interval: 2s
scrape_configs:
  # - job_name: "prometheus"
  #   static_configs:
  #     - targets: ["localhost:9090"]
  - job_name: "hasura"
    scrape_interval: 1s
    # metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8889"]
      # - targets: ["host.docker.internal:8888"]
